---
title: "_index.md"
author: "Nuri Park"
date: "9/14/2020"
output: html_document
---
---
authors:
- Nuri Park
bio: Hello! I am an undergraduate student at Wake Forest University majoring in B.S. Mathematical Statistics with double minors in chemistry, and health policy and administration. I am thrilled to work with Dr. McGowan for my senior thesis on developing the best way to teach R in classroom settings using randomized controlled trial. I am passionate about utilizing data and statistics to minimize health disparities and to improve the public health system in the U.S. 

education:
  courses:
  - course: B.S. in Mathematical Statistics
    institution: Wake Forest University
    year: Anticipated 2021

email: "parkn17@wfu.edu"
interests:
- R programming
- Biostatistics and Epidemiology
- Public Health
name: Nuri Park
organizations:
- name: Wake Forest University
  url: ""
role: Undergraduate Researcher
social:
- icon: envelope
  icon_pack: fas
  link: "parkn17@wfu.edu"
- icon: github
  icon_pack: fab
  link: https://github.com/nuripark10
superuser: true
title: Nuri Park
user_groups:
- Undergraduate Students
---

